### ISSUE TITLE
Slot props not defined in Typescript

### ISSUE THREAD

**Issue by chrisdhanaraj** [rgossiaux/svelte-headlessui#31]
Hello!

I've been tinkering with this library today and it's been great! One thing I've run into is that the packaging that's been done so far doesn't generate typings for the various `slotProps` that are used; i.e., the `slotProps` for `ListBoxOption` is `{}` instead of correctly picking up the `active/selected/disabled` props. 

Root cause here is spreading the `slotProps` onto the `slot`, instead of defining them manually. Looks like if you did something like the below, `sveltekit package` picks up the types correctly

```
<slot active={slotProps.active} ...etc/>
```

**Comment by rgossiaux** [comment]
Yep, this is due to this issue: https://github.com/sveltejs/language-tools/issues/1291

It's already been fixed, we're just waiting for a new release of the language tools which contains the fix. Not sure when that will be but hopefully it'll be soon.

**Comment by chrisdhanaraj** [comment]
Ohhh perfect 👍 Glad they fixed it at the tool source! Closing out the issue

**Comment by rgossiaux** [comment]
Going to leave this open until the fix is released, actually, for reference for other people who run into this.

**Comment by navtojchahal** [comment]
The fix seems to be released in [svelte2tsx-0.4.13](https://github.com/sveltejs/language-tools/releases/tag/svelte2tsx-0.4.13). Can someone else confirm this?
![image](https://user-images.githubusercontent.com/37762455/149607644-f69fb9a1-d737-4e8f-9bc4-824790c73f8f.png)

**Comment by bryanmylee** [comment]
`@rgossiaux/svelte-headlessui@1.0.0-beta.7` is still missing its slot definitions. Should we rebuild the project ourselves with the latest `svelte2tsx` and report back?

**Comment by rgossiaux** [comment]
This should be fixed in the latest release now.
